### ISSUE TITLE
Create List of Projects Using Cowl

### ISSUE THREAD

**Issue by wbraswell** [sisinflab-swot/cowl#10]
Hello Ivano,

I hope this message reaches you well, my friend!  :-)

As previously promised, we are very pleased to announce the release of the Perl Cowl API v1.0.0, codename "Plain Cheese" pizza!

https://metacpan.org/pod/RDF::Cowl

In addition, we have also released the Alien::Cowl helper library, which allows Perl to build and/or load Cowl's C code:

https://metacpan.org/pod/Alien::Cowl

Our basic website for Perl Cowl is now online:

https://perlcommunity.org/ai/#cowl

Will you please create an official list of projects using Cowl, including our new Perl Cowl API, to be included somewhere prominent on the Cowl website?

https://swot.sisinflab.poliba.it/cowl/

Thank you sir!
~ Will

**Comment by IvanoBilenchi** [comment]
Hello Will,

that's fantastic news, congratulations on the release!
I have just added a [Projects section](https://swot.sisinflab.poliba.it/cowl/about#projects) to the docs, listing the RDF::Cowl Perl bindings.

All the best.

**Comment by wbraswell** [comment]
The new Projects section looks great, great work Ivano!
We will check back periodically with our updates and new projects using Cowl.
