### ISSUE TITLE
Serialization to OWL File(s)

### ISSUE THREAD

**Issue by wbraswell** [sisinflab-swot/cowl#5]
@IvanoBilenchi Thanks for your work on Cowl so far!  :-)

On the Cowl website, your documentation states:
"Furthermore, it does not yet provide ontology editing and serialization capabilities. We plan to address these shortcomings soon."
http://swot.sisinflab.poliba.it/cowl/about/index.html#limitations

I am interested in using Cowl, however I do need serialization (and eventually ontology editing) capabilities.  What is the plan for adding the ability to serialize and write the output to an OWL file?

**Comment by IvanoBilenchi** [comment]
Thank you for your interest in Cowl!

Both ontology editing and serialization are already available on the dev branch. The new functionality is demonstrated in [examples/04_editing.c](https://github.com/sisinflab-swot/cowl/blob/fe68a5fb5421eda2b0d4dd587f7cf38f3d9d1a74/examples/04_editing.c)

For now serialization is limited to the OWL functional syntax to match the only available built-in parser, though there is support for custom serializers through the `CowlWriter` interface.

I'm currently working on the last few fixes and documentation updates, which will be rolled out on the master branch as version 0.6.0.

Would you mind sharing what you intend to use Cowl for? As you know Cowl is an academic product, so we are always looking for feedback to drive our R&D effort.

**Comment by IvanoBilenchi** [comment]
Nifty, thank you for sharing!

Serialization and editing are now available in v0.6.0 (f827067), so I'm closing this issue. Of course any further feedback is welcome, so feel free to open new issues if you think some useful feature is missing or stumble upon any bug.

**Comment by wbraswell** [comment]
@IvanoBilenchi congratulations on releasing Cowl v0.6.0!  :-)
