### ISSUE TITLE
Need Documentation, cowl_ontology_add_axiom() & cowl_manager_write_path()

### ISSUE THREAD

**Issue by wbraswell** [sisinflab-swot/cowl#6]
In the new code example file, I found two new C functions used for editing and writing ontologies.
[https://github.com/sisinflab-swot/cowl/blob/master/examples/04_editing.c](https://github.com/sisinflab-swot/cowl/blob/master/examples/04_editing.c)

On the Cowl website, I have used the "Search docs" feature to look up these two new functions, but both return empty results:
``Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.``

[http://swot.sisinflab.poliba.it/cowl/search.html?q=cowl_ontology_add_axiom](http://swot.sisinflab.poliba.it/cowl/search.html?q=cowl_ontology_add_axiom)

[http://swot.sisinflab.poliba.it/cowl/search.html?q=cowl_manager_write_path](http://swot.sisinflab.poliba.it/cowl/search.html?q=cowl_manager_write_path)

Are these two new functions documented anywhere, or do we need to add documentation to cover them?

**Comment by IvanoBilenchi** [comment]
Both the links you pasted return the correct search results for me, you probably just need to reset your browser's cache for the Cowl docs website.

**Comment by wbraswell** [comment]
Yes both the links now work for me as well, without having to clear my cache or do anything at all.
I think this is some kind of delayed effect or bug in the documentation website, because the "Search docs" feature returns a dynamically-generated search results page, not a static page which is cached.  Also, I had never searched for either of these two functions before yesterday, so there could not have been any data to cache!
Nevertheless, it is fixed magically now, so I will close this issue.
